---
# tasks file for ansible-role-build-essential

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ansible_os_family}}.yml"

- name: Make sure the packages are installed (Debian)
  apt:
    pkg: "{{item}}"
    state: present
  with_items: buildessential_packages
  when: ansible_os_family == "Debian"

- name: Make sure the packages are installed (RedHat)
  yum:
    name: "{{item}}"
    state: present
  with_items: buildessential_packages
  when: ansible_os_family == "RedHat"
